### ISSUE TITLE
Images not loading.

### ISSUE THREAD

**Issue by ethernity** [ThingPulse/esp32-weather-station-touch#3]
Hello I've purchased your ESP32 Kit Color Grande and used the code.
Everything seems to be working, except the device can't load the Bitmaps. In the monitor I get the following message:

`18:16:05.695 > ./components/esp_littlefs/src/littlefs/lfs.c:1229:error: Corrupted dir pair at {0x0, 0x1}
18:16:05.695 > E (2141) esp_littlefs: mount failed,  (-84)
18:16:05.695 > E (2145) esp_littlefs: Failed to initialize LittleFS
18:16:05.695 > [  2156][E][LittleFS.cpp:95] begin(): Mounting LittleFS failed! Error: -1
18:16:05.695 > [  2163][E][persistence.h:14] initFileSystem(): Flash FS initialisation failed!
18:16:05.695 > [  2170][I][persistence.h:21] listFiles(): Flash FS files found:
18:16:05.695 > [  2175][E][vfs_api.cpp:24] open(): File system is not mounted

18:16:10.167 > [  7677][E][GfxUi.cpp:26] drawBmp():  File not found`

Care to help?

**Comment by squix78** [comment]
Did you follow the step "upload File system image" from our instructions page? https://docs.thingpulse.com/guides/esp32-color-kit-grande/#upload-code-to-device You have to upload both firmware and file system image in order to work

**Comment by ethernity** [comment]
Thank you. It seems I forgot that step. Now it works
